### ISSUE TITLE
EBI Visual Framework v1.3 feature roadmap and timeline

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#103]
# 🚨**UPDATE**🚨
The EBI Visual Framework v1.3 will be released on Monday 2018 April 9.
- You can offer your thoughts on v1.4 at #130 
- See what's new, read the release notes at https://github.com/ebiwd/EBI-Framework/tree/v1.3#technical-changes
- Look at sample pages at https://www.ebi.ac.uk/style-lab/websites/sample-site/

---

You can see it in use at https://www.ebi.ac.uk/style-lab/

# High level
At a high level, this release will require minimal changes to the v1.2 HTML structure and focuses on polishing and optimising the visual framework with an eye to future EMBL brand updates and use of the Visual Framework by more independent groups.

# Target changes
All tickets for v1.3: https://github.com/ebiwd/EBI-Framework/milestone/3

## Strategic
- [x] Further separate EBI look from function of framework so that this can be of broader use (initial steps at https://github.com/ebiwd/Lifesciences-framework -- more to come in v1.4)
- [x] Utilise documentation systems for CSS and JS #117
- [x] Add ELIXIR banner support #116

## CSS and JS improvements
- [x] Update to Foundation 6.4, but keep CSS floats as our default
- [x] Offer minified versions of all JS/CSS #100 
- [x] Add 'external' href link style #110
- [x] Button grid odd right corners #95
- [x] Announcements improvements: Value prop and efficiency of downtime.js #26 
- [x] Improve loading of foundation, foundationExtendEBI, script.js  #77 
- [x] Black bar icons misaligned in v1.2/3 #111 
- [x] Methods and guidance on using the framework with react and angular (particularly methods on reinserting content as elements are updated) #115

## Content delivery improvements
- [x] Fully manage #masthead-black-bar in script.js #112
- [x] Improve presentation of EMBL selector (need to create issue)
- [x] Explore new EMBL font 
    - Fira: https://blogs.embl.org/communications/2017/07/17/selecting-a-new-typeface-for-embl-fira/
    - Discuss: https://github.com/ebiwd/EBI-Icon-fonts/issues/8

## Accessibility
- [x] Reduce number of 'skip-to' links #109
- [ ] Promote accessibility best practices #47 
- [x] Add visibile a:focus style  #99 

## Improved distribution
- [ ] Automatic updating of NPM (need to create separate issue)
- [x] Build Foundation Framework into main CSS files #107
- [x] Remove compliance compatibility file #108

### CSS and JS improvements
- Responsive menu sub-menu bug #50

### Improved distribution
- Add WebJar integration for Java sites #106

# Timeline
- [x] September: begin development
- [x] October: Roll feature plans, timeline
- [x] November (early): first alpha
- [x] December (middle): beta
- [x] February (middle): release candidate
- [ ] February (late): release

**Comment by khawkins98** [comment]
Now launched. Closing.
