### ISSUE TITLE
EBI Visual Framework v1.4 feature roadmap and timeline

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#130]
---

# ℹ️ Current status
- v1.4 is not yet in active development
- This is a draft list of proposed goals and timeframe

---

The [EBI Visual Framework v1.3](https://github.com/ebiwd/EBI-Framework/issues/103) will be released on Monday 9 April, so let's start collecting our thoughts for what's in v1.4.

# 🗼 High level
v1.4 will mainly look to be a structural and documentation release. In v1.2 and v1.3 we made much progress on the look of things, and now we want to improve the technical architecture of the build process and ensure our documentation is clear and helpful. "Documentation" includes expanding the pattern library.

## 🎯 Target changes
All tickets for v1.4: https://github.com/ebiwd/EBI-Framework/milestone/5

## 🗺 Strategic
- Continue to find ways to align with the proposed EMBL Design Language
- Continue to investigate what we need in an EMBL font
- Consider where it makes sense for services to diverge from the "corporate" brand
- Plan pattern library workshops/clinics
- Host regular developer on-boarding sessions
- Abstract core "Life Science" options from EBI brand (more to come on this)

## 🎨 CSS and JS improvements
- [ ] Update to latest version of Foundation
- [ ] Further methods and guidance on using the framework with react and angular (particularly methods on reinserting content as elements are updated) #115

## 📰 Content delivery improvements
- none yet
- [ ] Automatic updating of NPM (need to create separate issue)

## 🕶 Accessibility
- [ ] Promote accessibility best practices #47 
- Others?

## 😵 Bumped to v1.5
- Nothing yet

# 📆 Timeline
- [ ] April: planning
- [ ] May (late): begin development
- [ ] June: finalise feature plans, timeline
- [ ] August: first alpha
- [ ] September: beta
- October-November: RCs + release

**Comment by khawkins98** [comment]
Superseded by #162
