### ISSUE TITLE
Roadmap for v1.4

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#162]
As the VF 2.0 matures, we expect most new projects will make use of its new architecture and look. 

However there will be many existing projects that are unable to upgrade and will feel pressure to visually align with the newer look. 

A v1.4 release would be a way for services to opt in to visual changes like typeface and perhaps some colour changes, without needing to rearchitect their projects.

## high level features

- [ ] new EMBL and EBI Plex typeface
- [ ] thematic changes to header and footer
- [ ] compatibility optimisations for posting will with vf2.0 CSS that may be co-loaded into a project
- [ ] migration guide
- [ ] updates to Style Lab and notes on 1.x EOL
 
## Todo

- [ ] circulate plan with Web Guidelines Committee
- [ ] create 1.4 Dev branch

**Comment by khawkins98** [comment]
You can get a feel for 1.4 in the wild, it's been applied to the dev Style Lab: http://wwwdev.ebi.ac.uk/style-lab/general/templates/
