### ISSUE TITLE
EBI Visual Framework v1.2 roadmap

### ISSUE THREAD

**Issue by khawkins98** [ebiwd/EBI-Framework#61]
Planning is starting for v1.2 to be released in summer 2017 (likely late summer).

Here's a rundown of what's likely to be addressed:
- Don't theme off IDs #49 
- Continue iterating on the "lite" version #46 
  - Add Angular specific guidance #51
- Improve in-visible classes #30
- Improve stickiness of menu bar #28 
- Optimise foot.js script loading #24 #26
- Revisit spacing on black tab in global nav #21 
- Look at adding accessibility guidance #47
- Correct nesting of `#global-masthead` inside `#global-masthead`
- Update to most recent version of Foundation
- Consider removal of (redundant?) Modernizr

And a couple specific to the fonts
- Improve font distribution https://github.com/ebiwd/EBI-Icon-fonts/issues/6
- Revisit use of Helvetica as main font https://github.com/ebiwd/EBI-Icon-fonts/issues/8

We're looking to finalise this list at the 7 Feb Web Guidelines Committee, so if you have any suggestions or concerns, post them below or make a new issue.

We'll be sure to update this ticket with any updates.

Timeline:
- 7 Feb: Review feature list for approval at the WGC meeting
- Late Feb: dev testing releases for v1.2 to begin 
- March: bi-weekly clinics to begin
- Late March: first alpha
- April: First beta, feature freeze
- June: Release candidate
- July: Migrate pattern library to v1.2
- Aug: Target release

**Comment by khawkins98** [comment]
Raised in recent discussions:
- Wider desktop default: from 75rem (1180px) to 80rem (1260px)
- Import v1.1's `table.data-table` support: https://github.com/ebiwd/EBI-Framework/issues/65

**Comment by khawkins98** [comment]
To the pattern library I've added made a clone of the boilerplate pages that use the dev v1.2 framework ( https://ebiwd.github.io/EBI-Pattern-library/sample-site-v1.2/ )

Of note:
- Sample lite integration: https://ebiwd.github.io/EBI-Pattern-library/sample-site-v1.2/boilerplate/lite.html
- Sample bootstrap integration: https://ebiwd.github.io/EBI-Pattern-library/sample-site-v1.2/boilerplate/bootstrap.html

Far more work to do on both of those, but they show initial success.

**Comment by khawkins98** [comment]
I've rolled the first alpha! 🎇

Release notes: https://github.com/ebiwd/EBI-Framework/releases/tag/v1.2-alpha.1

**Comment by khawkins98** [comment]
A few new contenders from the 19 April Framework Clinic:
- [ ] Add a multi-select UI component #79
- [ ] Improve grouping of masthead and footer divs #80
- [ ] Add EBI Visual Framework to NPM #81 
- [ ] Break apart script.js into separate concerns #82
- [ ] Extract content into include files #83

**Comment by khawkins98** [comment]
There is now a sample how-to migration from v1.1 to v1.2: https://github.com/ebiwd/EBI-Framework/issues/85

**Comment by khawkins98** [comment]
[Alpha 4 has now been released](https://github.com/ebiwd/EBI-Framework/releases/tag/v1.2-alpha.4) and pending next week's discussion at the Web Guidelines Committee we could have a first beta in early/mid May.
